tourney-test: ../../model/Tournament.h ../../model/Tournament.cpp ../../model/Round.h ../../model/Round.cpp main.cpp
	g++ -o tourney-test ../../model/Tournament.h ../../model/Tournament.cpp ../../model/Round.h ../../model/Round.cpp main.cpp -I.
