deck-test: ../../model/Deck.h ../../model/Deck.cpp ../../model/Card.h ../../model/Card.cpp main.cpp
	g++ -std=c++0x -o deck-test ../../model/Deck.h ../../model/Deck.cpp ../../model/Card.h ../../model/Card.cpp main.cpp -I.

